"""
Confidence-cascading pipeline with uncertainty propagation.

What problem this solves
------------------------
The Phase-1 pipeline (``src/pipeline.py``) treats every stage as if its
output were ground truth. When the CRF places a sentence boundary in the
wrong position, the safety guardrail silently sees a different sentence
structure and may approve a recipe whose toxic ingredient is now
"orphaned" from its purification step. This is the *cascading-failure*
problem identified in ``docs/FULL_AUDIT_REPORT.md`` §2.4 and in the
thesis (§5.1 "Cascading Failures").

The cascade pipeline:

1.  Emits a per-token confidence from the segmenter
    (CRF marginal probability or RoBERTa softmax score).
2.  Computes a sequence-level *segmentation reliability* score from the
    margin of the per-token predictions.
3.  Passes both the segmented text *and* the reliability score into the
    safety guardrail.
4.  The guardrail returns one of three verdicts:
        APPROVE   — toxic entities present and purified, high confidence
        REJECT    — toxic entity without purification (hard veto)
        HITL      — uncertain segmentation OR borderline KG match;
                    human-in-the-loop review required
5.  An auditable *evidence chain* is attached to every verdict so the
    practitioner sees *why* the system decided.

Novelty
-------
The HITL verdict is generated by a calibrated joint criterion on
segmentation reliability and KG-match strength. This is the
"Safety-Risk-vs-HITL-Coverage" curve we plot in the evaluation: as the
HITL threshold τ relaxes, more borderline cases auto-pass at the cost of
missed toxicity flags. The optimal operating point is the Pareto front.
"""
from __future__ import annotations

import csv
import math
import os
from dataclasses import dataclass, field
from typing import Callable, List, Optional, Tuple

from config import (
    CRF_THRESHOLD_DEFAULT,
    DATA_DIR,
    MODELS_DIR,
    SAFETY_DEFAULT_WINDOW,
    normalize_sinhala,
)


# ---------------------------------------------------------------------------
# Data classes describing each stage's output
# ---------------------------------------------------------------------------
@dataclass
class SegmentationResult:
    """Output of the SBD stage."""

    words: List[str]
    stop_probs: List[float]
    threshold: float
    segmented_text: str
    reliability: float = 0.0  # 0..1 sequence-level confidence
    method: str = "unknown"   # 'crf' | 'roberta' | 'rule'

    @property
    def sentences(self) -> List[str]:
        return [s.strip() for s in self.segmented_text.split(".") if s.strip()]


@dataclass
class SafetyVerdict:
    final_status: str          # APPROVE | REJECT | HITL
    issues_count: int
    seg_reliability: float
    hitl_reason: Optional[str] = None
    details: List[dict] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Confidence helpers
# ---------------------------------------------------------------------------
def per_token_confidence(stop_probs: List[float], threshold: float) -> List[float]:
    """Margin from the decision boundary, per token, mapped to [0, 1]."""
    out = []
    for p in stop_probs:
        # Distance from threshold, scaled by the larger of the two regions
        if p >= threshold:
            denom = max(1.0 - threshold, 1e-6)
            out.append(min(1.0, (p - threshold) / denom))
        else:
            denom = max(threshold, 1e-6)
            out.append(min(1.0, (threshold - p) / denom))
    return out


def sequence_reliability(stop_probs: List[float], threshold: float) -> float:
    """Aggregate per-token margins into a 0..1 sequence reliability.

    We use the *minimum* per-token confidence (a chain is only as
    reliable as its weakest link) blended with the *mean* confidence, so
    a single uncertain token doesn't collapse the score for a long
    otherwise-confident sequence.
    """
    if not stop_probs:
        return 0.0
    margins = per_token_confidence(stop_probs, threshold)
    mn = min(margins)
    mu = sum(margins) / len(margins)
    return 0.4 * mn + 0.6 * mu


# ---------------------------------------------------------------------------
# Segmentation adapters
# ---------------------------------------------------------------------------
def segment_with_crf(
    text: str,
    crf,
    threshold: float = CRF_THRESHOLD_DEFAULT,
) -> SegmentationResult:
    """Adapter from a fitted sklearn-crfsuite CRF to SegmentationResult."""
    from pipeline import sent2features  # local import to avoid cycle at module load

    text = normalize_sinhala(text.strip())
    words = text.split() if text else []
    if not words:
        return SegmentationResult([], [], threshold, "", reliability=1.0, method="crf")

    dummy_sent = [(w, "") for w in words]
    features = [sent2features(dummy_sent)]
    marginals = crf.predict_marginals(features)[0]
    stop_probs = [float(m.get("STOP", 0.0)) for m in marginals]

    segmented_words = [w + "." if p > threshold else w for w, p in zip(words, stop_probs)]
    seg_text = " ".join(segmented_words)
    rel = sequence_reliability(stop_probs, threshold)
    return SegmentationResult(words, stop_probs, threshold, seg_text, reliability=rel, method="crf")


def segment_with_callable(
    text: str,
    predict_probs: Callable[[List[str]], List[float]],
    threshold: float = 0.5,
    method: str = "callable",
) -> SegmentationResult:
    """Generic adapter for any model that maps List[str] → per-word P(STOP)."""
    text = normalize_sinhala(text.strip())
    words = text.split() if text else []
    if not words:
        return SegmentationResult([], [], threshold, "", reliability=1.0, method=method)
    stop_probs = list(map(float, predict_probs(words)))
    segmented_words = [w + "." if p > threshold else w for w, p in zip(words, stop_probs)]
    seg_text = " ".join(segmented_words)
    rel = sequence_reliability(stop_probs, threshold)
    return SegmentationResult(words, stop_probs, threshold, seg_text, reliability=rel, method=method)


# ---------------------------------------------------------------------------
# Safety guardrail with HITL escalation
# ---------------------------------------------------------------------------
def load_knowledge_graph(csv_filepath: str = None) -> Optional[dict]:
    """Identical schema to `src/pipeline.load_knowledge_graph` so the two
    pipelines can share a KG file. Documented here to make the cascade
    self-contained."""
    if csv_filepath is None:
        csv_filepath = os.path.join(DATA_DIR, "ayurvedic_ingredients_full.csv")
    if not os.path.isfile(csv_filepath):
        return None
    kg: dict = {}
    with open(csv_filepath, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            entity = normalize_sinhala(row["Entity"].strip())
            tox = row["Toxicity"].strip().lower()
            if tox in {"low", "none", "safe", "no", ""}:
                continue
            aliases = [normalize_sinhala(a.strip()) for a in row["Aliases"].split(",") if a.strip()]
            shodh = [normalize_sinhala(p.strip()) for p in row["Purification_Keywords"].split(",") if p.strip()]
            if not shodh:
                continue
            kg[entity] = {
                "aliases": aliases,
                "toxicity": row["Toxicity"].strip(),
                "shodhana_keywords": shodh,
            }
    return kg


NEGATION_PATTERNS = ["නොමැති", "එපා", "නොකර", "නොකරන්න", "නොකරයි"]


def cascade_safety(
    seg: SegmentationResult,
    kg: dict,
    *,
    window_size: int = SAFETY_DEFAULT_WINDOW,
    hitl_min_seg_reliability: float = 0.55,
    hitl_min_kg_match_chars: int = 3,
) -> SafetyVerdict:
    """KG safety with confidence-aware HITL escalation.

    Decision rule
    -------------
    1. Build an evidence record for every toxic entity mention found.
    2. Categorise each mention:
         a. shodhana found and NOT negated     → safe
         b. shodhana found but negated         → unsafe
         c. shodhana not found                 → unsafe
    3. If at least one mention is unsafe ⇒ REJECT (hard veto).
    4. Else if `seg.reliability < hitl_min_seg_reliability` ⇒ HITL
       (segmenter is too uncertain for the guardrail to trust its
       sentence-window logic).
    5. Else APPROVE.
    """
    sentences = seg.sentences
    issues = 0
    details: List[dict] = []

    # Build longest-first term list
    term_to_data = {}
    all_terms = []
    for entity, data in kg.items():
        for t in [entity] + data["aliases"]:
            if t not in term_to_data:
                all_terms.append(t)
                term_to_data[t] = (entity, data)
    all_terms.sort(key=len, reverse=True)

    for i, sent in enumerate(sentences):
        scratch = f" {sent} "
        found = []
        for t in all_terms:
            if f" {t} " in scratch:
                _, data = term_to_data[t]
                found.append((t, data))
                scratch = scratch.replace(f" {t} ", " [MASK] ")
        for t, data in found:
            lo = max(0, i - window_size)
            hi = min(len(sentences), i + window_size + 1)
            context = " ".join(sentences[lo:hi])
            has_shodh = any(k in context for k in data["shodhana_keywords"])
            has_neg = any(n in context for n in NEGATION_PATTERNS)
            if has_shodh and not has_neg:
                details.append({"term": t, "sentence_id": i + 1, "status": "PASS",
                                 "evidence": [k for k in data["shodhana_keywords"] if k in context]})
            else:
                issues += 1
                why = "negated_shodhana" if has_neg else "missing_shodhana"
                details.append({"term": t, "sentence_id": i + 1, "status": "ALERT",
                                 "reason": why,
                                 "evidence": []})

    if issues > 0:
        return SafetyVerdict(
            final_status="REJECT",
            issues_count=issues,
            seg_reliability=seg.reliability,
            details=details,
        )

    if seg.reliability < hitl_min_seg_reliability and details:
        # KG matches found but segmenter wasn't confident enough
        return SafetyVerdict(
            final_status="HITL",
            issues_count=0,
            seg_reliability=seg.reliability,
            hitl_reason=f"segmenter_reliability={seg.reliability:.3f} below τ={hitl_min_seg_reliability}",
            details=details,
        )

    return SafetyVerdict(
        final_status="APPROVE",
        issues_count=0,
        seg_reliability=seg.reliability,
        details=details,
    )


# ---------------------------------------------------------------------------
# Convenience end-to-end runner
# ---------------------------------------------------------------------------
def run_pipeline_crf(
    text: str,
    *,
    crf_path: str = None,
    kg_path: str = None,
    crf_threshold: float = CRF_THRESHOLD_DEFAULT,
    safety_window: int = SAFETY_DEFAULT_WINDOW,
    hitl_min_seg_reliability: float = 0.55,
) -> Tuple[SegmentationResult, SafetyVerdict]:
    """Convenience helper: load CRF + KG, run end-to-end cascade."""
    import joblib

    if crf_path is None:
        crf_path = os.path.join(MODELS_DIR, "ayurvedic_segmenter.pkl")
    if kg_path is None:
        kg_path = os.path.join(DATA_DIR, "ayurvedic_ingredients_full.csv")

    crf = joblib.load(crf_path)
    seg = segment_with_crf(text, crf, threshold=crf_threshold)
    kg = load_knowledge_graph(kg_path)
    verdict = cascade_safety(
        seg, kg or {},
        window_size=safety_window,
        hitl_min_seg_reliability=hitl_min_seg_reliability,
    )
    return seg, verdict
